feat: Swift source lines computation
insideapp-oss/sonar-apple pull request #5
Opened 2022-04-19 08:23 UTC by gaelfoppolo

# Description

- [ ] Implement a SourceLinesVisitor
- [ ] Call SourceLinesVisitor from SwiftSensor

# References

- https://github.com/insideapp-oss/sonar-flutter/blob/develop/dart-lang/src/main/java/fr/insideapp/sonarqube/dart/lang/antlr/SourceLinesVisitor.java
- https://github.com/insideapp-oss/sonar-flutter/blob/develop/dart-lang/src/main/java/fr/insideapp/sonarqube/dart/lang/DartSensor.java

# DoD

- [ ] Unit tests
- [ ] Documentation (and developer documentation) update

2022-04-26 15:59 UTC, zippy1978 requested changes

2022-04-26 15:59 UTC, zippy1978 commented on swift-lang/src/main/java/fr/insideapp/sonarqube/swift/lang/antlr/SourceLinesVisitor.java
> +        // only keeping the comments that are "pure" comments
Capitalize comments :) (like in other source files)

2022-04-26 15:59 UTC, zippy1978 commented on swift-lang/src/main/java/fr/insideapp/sonarqube/swift/lang/antlr/SwiftAntlrContext.java
> +        loadFromStreams(file, file.inputStream(), file.inputStream(), charset);
Move to parent class AntlrContext

2022-04-27 07:53 UTC, gaelfoppolo commented on swift-lang/src/main/java/fr/insideapp/sonarqube/swift/lang/antlr/SwiftAntlrContext.java
> +        loadFromStreams(file, file.inputStream(), file.inputStream(), charset);
Done!

2022-04-27 07:57 UTC, zippy1978 approved these changes

2022-04-27 07:59 UTC, merged