feat(ObjC): Objective-C language support
insideapp-oss/sonar-apple pull request #8
Opened 2022-04-23 15:56 UTC by zippy1978

2022-04-23 19:02 UTC, gaelfoppolo requested changes

2022-04-23 19:02 UTC, gaelfoppolo commented on commons/src/test/java/fr/insideapp/sonarqube/apple/commons/issues/JSONRulesDefinitionTest.java
> +
Remove one empty line.

2022-04-23 20:54 UTC, zippy1978 commented on commons/src/main/java/fr/insideapp/sonaqube/apple/commons/antlr/AntlrContext.java
> +package fr.insideapp.sonaqube.apple.commons.antlr;
Nice !
Did not see that :)

2022-04-23 20:55 UTC, zippy1978 commented on objc-lang/src/main/java/fr/insideapp/sonarqube/objc/lang/issues/ObjectiveCProfile.java
> +        // SwiftLint rules
👍

2022-04-23 20:56 UTC, zippy1978 commented on commons/src/test/java/fr/insideapp/sonarqube/apple/commons/issues/JSONRulesDefinitionTest.java
> +
👍

2022-04-23 21:03 UTC, zippy1978 commented on objc-lang/src/main/java/fr/insideapp/sonarqube/objc/lang/issues/oclint/OCLintRulesDefinition.java
> +        super(REPOSITORY_KEY, REPOSITORY_NAME, ObjectiveC.KEY, "/oclint-rules.json");
Sure !
did it for SwiftLint as well

2022-04-24 10:08 UTC, gaelfoppolo approved these changes

2022-04-24 10:32 UTC, merged